#!/usr/bin/env bash
# Displays list of currently running processes
# show all processes, for all users, including those which might not have a TTY
# Display in user-oriented format
# Show process heirachy

ps auxf
